snazy2000/SnipeitPS

PSScriptAnalyzerSettings.psd1, SnipeitPS/Public/New-User.ps1, Tests/SnipeItPS.Tests.ps1
=> Fix missing password  #9

SnipeitPS/Public/New-User.ps1
=> Set password_confirmation to password when ldap is false

SnipeitPS/Public/Set-Asset.ps1
The API supports a 'PUT' for modifying parts of an asset, but most of the supported fields were missing (I need to be able to set a location for example which was missing).  I've added all the current API fields and replaced the $values section with Get-ParameterValue.  Not fully tested everything but looking good so far.
=> Updated for current API fields

SnipeitPS/Public/Get-Accessory.ps1, SnipeitPS/Public/Get-Asset.ps1, SnipeitPS/Public/Get-AssetMaintenance.ps1, SnipeitPS/Public/Get-Category.ps1, SnipeitPS/Public/Get-Company.ps1, SnipeitPS/Public/Get-Component.ps1, SnipeitPS/Public/Get-CustomField.ps1, SnipeitPS/Public/Get-Department.ps1, SnipeitPS/Public/Get-License.ps1, SnipeitPS/Public/Get-Manufacturer.ps1, SnipeitPS/Public/Get-Model.ps1, SnipeitPS/Public/Get-SnipeitLocation.ps1, SnipeitPS/Public/Get-Status.ps1, SnipeitPS/Public/Get-Supplier.ps1, SnipeitPS/Public/Get-User.ps1
Get all items with -all switch
=> Get all for every get

SnipeitPS/Private/Invoke-SnipeitMethod.ps1
Reverts snazy2000/SnipeitPS#93.
Ups. I should think this again.
=> Revert "If api request to snipe  fails, don't continue, just throw error"

SnipeitPS/Public/Get-Accessory.ps1, SnipeitPS/Public/Get-Asset.ps1, SnipeitPS/Public/Get-AssetMaintenance.ps1, SnipeitPS/Public/Get-Category.ps1, SnipeitPS/Public/Get-Company.ps1, SnipeitPS/Public/Get-Component.ps1, SnipeitPS/Public/Get-Department.ps1, SnipeitPS/Public/Get-License.ps1, SnipeitPS/Public/Get-Manufacturer.ps1, SnipeitPS/Public/Get-Model.ps1, SnipeitPS/Public/Get-SnipeitLocation.ps1, SnipeitPS/Public/Get-Status.ps1, SnipeitPS/Public/Get-Supplier.ps1, SnipeitPS/Public/New-Category.ps1, SnipeitPS/Public/New-Location.ps1, SnipeitPS/Public/New-User.ps1, SnipeitPS/Public/Set-Components.ps1, SnipeitPS/Public/Set-SnipeitLocation.ps1
Clean up some whitespace left by previous changes.
=> remove whitespace

appveyor.yml
As there are many changes in develop it's time to update version up.
=> Version bump to 1.1.x

SnipeitPS/Private/Get-SnipeItAlias.ps1, SnipeitPS/Private/Set-SnipeItAlias.ps1, SnipeitPS/Private/Test-SnipeItAlias.ps1, SnipeitPS/Public/Update-SnipeItAlias.ps1, SnipeitPS/SnipeItPS.psd1, docs/SnipeItPS.md, docs/Update-SnipeItAlias.md
Helper function to update existing SnipeItPS scripts.
Get-Content [your-script.ps1] | Update-SnipeItAlias | Out-File [new-script-name.ps1]
=> Helper function to update existing SnipeItPS scripts

CHANGELOG.md, SnipeitPS/SnipeItPS.psd1, appveyor.yml
=> Version to 1.2.x

SnipeitPS/SnipeItPS.psm1
Cleaned out  left over variable
=> Get-SnipeItAlias provides this now

SnipeitPS/Public/New-SnipeItAsset.ps1, SnipeitPS/Public/Remove-SnipeItAsset.ps1, SnipeitPS/Public/Remove-SnipeItAssetMaintenance.ps1, SnipeitPS/Public/Remove-SnipeItUser.ps1, SnipeitPS/Public/Set-SnipeItAsset.ps1, SnipeitPS/Public/Set-SnipeItComponents.ps1, docs/New-SnipeItAsset.md, docs/Remove-SnipeItAsset.md, docs/Remove-SnipeItUser.md, docs/Set-SnipeItAsset.md, docs/Set-SnipeItComponent.md
Check that int field are inputted as int.
Also check that  datetimes are converted to string before calling snipeit api.
=> check datetime and int input types

SnipeitPS/Private/Invoke-SnipeitMethod.ps1
Goal for this  is to get more meaning full error messages.
=> Wrapped json parsing with try/catch

SnipeitPS/Public/Get-SnipeItActivity.ps1, SnipeitPS/SnipeItPS.psd1, docs/Get-SnipeItActivity.md, docs/Get-SnipeItComponent.md, docs/Get-SnipeItManufacturer.md, docs/New-SnipeItAsset.md, docs/New-SnipeItUser.md, docs/Set-SnipeItLicenseSeat.md, docs/Set-SnipeItUser.md, docs/SnipeItPS.md
Added support for reports/activity api.
Search checkout and checkin history, asssets updates, location changes etc.
=> Added Get-SnipeitActivity

CHANGELOG.md, SnipeitPS/Public/Get-SnipeItActivity.ps1, SnipeitPS/Public/Set-SnipeItAsset.ps1, SnipeitPS/SnipeItPS.psd1, appveyor.yml, docs/Get-SnipeItActivity.md, docs/Get-SnipeItComponent.md, docs/Get-SnipeItManufacturer.md, docs/New-SnipeItAsset.md, docs/New-SnipeItUser.md, docs/Set-SnipeItAsset.md, docs/Set-SnipeItLicenseSeat.md, docs/Set-SnipeItUser.md, docs/SnipeItPS.md
=> Version to 1.4

SnipeitPS/Public/Get-SnipeItAsset.ps1, SnipeitPS/Public/Get-SnipeItLicense.ps1, SnipeitPS/Public/New-SnipeItAccessory.ps1, SnipeitPS/Public/Set-SnipeItAccessory.ps1, SnipeitPS/Public/Set-SnipeItAccessoryOwner.ps1, SnipeitPS/Public/Set-SnipeItAsset.ps1, SnipeitPS/Public/Set-SnipeItAssetOwner.ps1, SnipeitPS/Public/Set-SnipeItLicense.ps1, SnipeitPS/Public/Set-SnipeItLicenseSeat.ps1, SnipeitPS/Public/Set-SnipeItLocation.ps1, SnipeitPS/Public/Set-SnipeItModel.ps1, SnipeitPS/Public/Set-SnipeItUser.ps1
Some how module changes were missing last commit
=> Pipeline support for Set functions

SnipeitPS/Public/Set-SnipeitLicenseSeat.ps1
=> assigned_id -> assigned_to

SnipeitPS/Public/Get-SnipeitLicense.ps1
Default parameter missing from parameter validation.
=> fix sort parameter

SnipeitPS/Public/New-SnipeitAsset.ps1, SnipeitPS/Public/Set-SnipeitAsset.ps1, docs/New-SnipeitAsset.md, docs/Set-SnipeitAsset.md, docs/Set-SnipeitLicenseSeat.md
Example was refering CustomValues while we are using customfields attribute.
=> corrected examples

SnipeitPS/Public/Remove-SnipeitAccessory.ps1, SnipeitPS/Public/Remove-SnipeitAssetMaintenance.ps1, SnipeitPS/Public/Remove-SnipeitCategory.ps1, SnipeitPS/Public/Remove-SnipeitCompany.ps1, SnipeitPS/Public/Remove-SnipeitComponent.ps1, SnipeitPS/Public/Remove-SnipeitCustomField.ps1, SnipeitPS/Public/Remove-SnipeitDepartment.ps1, SnipeitPS/Public/Remove-SnipeitLicense.ps1, SnipeitPS/Public/Remove-SnipeitLocation.ps1, SnipeitPS/Public/Remove-SnipeitManufacturer.ps1, SnipeitPS/Public/Remove-SnipeitModel.ps1, SnipeitPS/Public/Remove-SnipeitUser.ps1, SnipeitPS/SnipeitPS.psd1, docs/Get-SnipeitAsset.md, docs/New-SnipeitAsset.md, docs/Remove-SnipeitAccessory.md, docs/Remove-SnipeitAsset.md, docs/Remove-SnipeitCompany.md, docs/Remove-SnipeitComponent.md, docs/Remove-SnipeitCustomField.md, docs/Remove-SnipeitDepartment.md, docs/Remove-SnipeitLicense.md, docs/Remove-SnipeitLocation.md, docs/Remove-SnipeitManufacturer.md, docs/Remove-SnipeitModel.md, docs/Set-SnipeitAsset.md, docs/SnipeitPS.md
=> Remove new item types

SnipeitPS/Public/Get-SnipeitConsumable.ps1, SnipeitPS/Public/New-SnipeitConsumable.ps1, SnipeitPS/Public/Remove-SnipeitConsumable.ps1, SnipeitPS/Public/Set-SnipeitConsumable.ps1, SnipeitPS/SnipeitPS.psd1, docs/Get-SnipeitConsumable.md, docs/New-SnipeitCompany.md, docs/New-SnipeitConsumable.md, docs/Remove-SnipeitConsumable.md, docs/Set-SnipeitConsumable.md, docs/SnipeitPS.md
create, set, get and remove consumables.
=> added support for consumables

SnipeitPS/Public/Get-SnipeitAsset.ps1
Mixed serial with asset_serial alias.
=> Fix get with serial

SnipeitPS/Public/Set-SnipeitLicenseSeat.ps1
Added example how to checkin licenses
=> Added example how to checkin licenses

SnipeitPS/Public/New-SnipeitAccessory.ps1, SnipeitPS/Public/Set-SnipeitAccessory.ps1, docs/New-SnipeitAccessory.md, docs/Set-SnipeitAccessory.md
Set model_number for accessories.  Setting min_amt will work after snipe it api support its, currently it's missing from api.
=> set model_number and min_amt

SnipeitPS/Private/Invoke-SnipeitMethod.ps1
=> removed debug proxy

SnipeitPS/Private/Invoke-SnipeitMethod.ps1
=> allow empty body

CHANGELOG.md, README.md, SnipeitPS/Private/Invoke-SnipeitMethod.ps1
Fix content encoding bug introduced on 1.9 release.
=> Fix/content encoding #218 introduced on 1.9 release

SnipeitPS/SnipeitPS.psd1, appveyor.yml
=> Version 1.10.x

SnipeitPS/Public/Get-SnipeitFieldset.ps1, SnipeitPS/Public/Get-SnipeitLicense.ps1
Project or actualy I really need test framework.
=> fix typo #277

SnipeitPS/Private/Invoke-SnipeitMethod.ps1
Fail request when snipe it api returns unauthorized.
=> Fail when request is unauthorized

SnipeitPS/Public/New-SnipeitAudit.ps1
Added  Next Audit Date to New-SnipeItAudit.ps1 from [RussellLeVasseur](https://github.com/RussellLeVasseur)
=> @RussellLeVasseur :  Add Next Audit Date to New-SnipeItAudit.ps1 

SnipeitPS/Public/New-SnipeitAsset.ps1, SnipeitPS/Public/Set-SnipeitAsset.ps1, docs/New-SnipeitAsset.md, docs/Set-SnipeitAsset.md
=> Added set supplier_id to Set-SnipeitAsset

SnipeitPS/Public/New-SnipeitUser.ps1, SnipeitPS/Public/Set-SnipeitUser.ps1
Ok looks like 4th time is the charm...
Added ability to assign a user to groups on or after creation with New/Set-SnipeitUser
=> Add Groups to New/Set-SnipeitUser.ps1

SnipeitPS/Public/Get-SnipeitAccessory.ps1, SnipeitPS/Public/Get-SnipeitAsset.ps1, SnipeitPS/Public/Get-SnipeitCategory.ps1, SnipeitPS/Public/Get-SnipeitCompany.ps1, SnipeitPS/Public/Get-SnipeitComponent.ps1, SnipeitPS/Public/Get-SnipeitConsumable.ps1, SnipeitPS/Public/Get-SnipeitDepartment.ps1, SnipeitPS/Public/Get-SnipeitLocation.ps1, SnipeitPS/Public/Get-SnipeitManufacturer.ps1, SnipeitPS/Public/Get-SnipeitStatus.ps1, SnipeitPS/Public/Get-SnipeitSupplier.ps1, SnipeitPS/Public/Get-SnipeitUser.ps1
* Add additional parameters to Get functions, especially -name wherever possible.
* Add some missing function help
=> Update Get Functions
